export interface WordEntry {
  word: string;
  category: string;
  difficulty: 1 | 2 | 3;
}

export const DRAW_WORDS: WordEntry[] = [
  // animais
  { word: "cachorro", category: "animal", difficulty: 1 },
  { word: "gato", category: "animal", difficulty: 1 },
  { word: "elefante", category: "animal", difficulty: 1 },
  { word: "girafa", category: "animal", difficulty: 1 },
  { word: "leao", category: "animal", difficulty: 1 },
  { word: "tigre", category: "animal", difficulty: 1 },
  { word: "urso", category: "animal", difficulty: 1 },
  { word: "coelho", category: "animal", difficulty: 1 },
  { word: "cavalo", category: "animal", difficulty: 1 },
  { word: "vaca", category: "animal", difficulty: 1 },
  { word: "porco", category: "animal", difficulty: 1 },
  { word: "galinha", category: "animal", difficulty: 1 },
  { word: "pato", category: "animal", difficulty: 1 },
  { word: "peixe", category: "animal", difficulty: 1 },
  { word: "tubarao", category: "animal", difficulty: 2 },
  { word: "polvo", category: "animal", difficulty: 2 },
  { word: "caranguejo", category: "animal", difficulty: 2 },
  { word: "borboleta", category: "animal", difficulty: 2 },
  { word: "abelha", category: "animal", difficulty: 2 },
  { word: "aranha", category: "animal", difficulty: 2 },
  { word: "cobra", category: "animal", difficulty: 1 },
  { word: "sapo", category: "animal", difficulty: 1 },
  { word: "tartaruga", category: "animal", difficulty: 2 },
  { word: "crocodilo", category: "animal", difficulty: 2 },
  { word: "macaco", category: "animal", difficulty: 1 },
  { word: "zebra", category: "animal", difficulty: 1 },
  { word: "canguru", category: "animal", difficulty: 2 },
  { word: "coruja", category: "animal", difficulty: 2 },
  { word: "pinguim", category: "animal", difficulty: 1 },
  { word: "morcego", category: "animal", difficulty: 2 },
  { word: "esquilo", category: "animal", difficulty: 2 },
  { word: "rato", category: "animal", difficulty: 1 },
  { word: "lobo", category: "animal", difficulty: 1 },
  { word: "raposa", category: "animal", difficulty: 2 },
  { word: "ovelha", category: "animal", difficulty: 1 },
  { word: "camelo", category: "animal", difficulty: 2 },
  { word: "rinoceronte", category: "animal", difficulty: 2 },
  { word: "hipopotamo", category: "animal", difficulty: 2 },
  { word: "papagaio", category: "animal", difficulty: 2 },
  { word: "aguia", category: "animal", difficulty: 2 },

  // objetos
  { word: "cadeira", category: "objeto", difficulty: 1 },
  { word: "mesa", category: "objeto", difficulty: 1 },
  { word: "porta", category: "objeto", difficulty: 1 },
  { word: "janela", category: "objeto", difficulty: 1 },
  { word: "livro", category: "objeto", difficulty: 1 },
  { word: "caneta", category: "objeto", difficulty: 1 },
  { word: "lapis", category: "objeto", difficulty: 1 },
  { word: "telefone", category: "objeto", difficulty: 1 },
  { word: "computador", category: "objeto", difficulty: 2 },
  { word: "relogio", category: "objeto", difficulty: 1 },
  { word: "oculos", category: "objeto", difficulty: 1 },
  { word: "chapeu", category: "objeto", difficulty: 1 },
  { word: "sapato", category: "objeto", difficulty: 1 },
  { word: "camisa", category: "objeto", difficulty: 1 },
  { word: "mochila", category: "objeto", difficulty: 1 },
  { word: "guarda-chuva", category: "objeto", difficulty: 2 },
  { word: "espelho", category: "objeto", difficulty: 1 },
  { word: "chave", category: "objeto", difficulty: 1 },
  { word: "garrafa", category: "objeto", difficulty: 1 },
  { word: "copo", category: "objeto", difficulty: 1 },
  { word: "prato", category: "objeto", difficulty: 1 },
  { word: "faca", category: "objeto", difficulty: 1 },
  { word: "garfo", category: "objeto", difficulty: 1 },
  { word: "colher", category: "objeto", difficulty: 1 },
  { word: "panela", category: "objeto", difficulty: 1 },
  { word: "televisao", category: "objeto", difficulty: 2 },
  { word: "sofa", category: "objeto", difficulty: 1 },
  { word: "cama", category: "objeto", difficulty: 1 },
  { word: "travesseiro", category: "objeto", difficulty: 2 },
  { word: "escova", category: "objeto", difficulty: 1 },
  { word: "sabao", category: "objeto", difficulty: 1 },
  { word: "toalha", category: "objeto", difficulty: 1 },
  { word: "vela", category: "objeto", difficulty: 1 },
  { word: "lampada", category: "objeto", difficulty: 1 },
  { word: "tesoura", category: "objeto", difficulty: 1 },
  { word: "martelo", category: "objeto", difficulty: 1 },
  { word: "escada", category: "objeto", difficulty: 1 },
  { word: "bandeira", category: "objeto", difficulty: 2 },
  { word: "balde", category: "objeto", difficulty: 1 },
  { word: "vassoura", category: "objeto", difficulty: 1 },
  { word: "mala", category: "objeto", difficulty: 1 },
  { word: "carteira", category: "objeto", difficulty: 1 },
  { word: "anel", category: "objeto", difficulty: 1 },
  { word: "coroa", category: "objeto", difficulty: 1 },
  { word: "bola", category: "objeto", difficulty: 1 },
  { word: "pipa", category: "objeto", difficulty: 1 },
  { word: "boneca", category: "objeto", difficulty: 1 },

  // comida
  { word: "pizza", category: "comida", difficulty: 1 },
  { word: "hamburguer", category: "comida", difficulty: 1 },
  { word: "sorvete", category: "comida", difficulty: 1 },
  { word: "bolo", category: "comida", difficulty: 1 },
  { word: "pao", category: "comida", difficulty: 1 },
  { word: "queijo", category: "comida", difficulty: 1 },
  { word: "ovo", category: "comida", difficulty: 1 },
  { word: "banana", category: "comida", difficulty: 1 },
  { word: "maca", category: "comida", difficulty: 1 },
  { word: "uva", category: "comida", difficulty: 1 },
  { word: "melancia", category: "comida", difficulty: 1 },
  { word: "abacaxi", category: "comida", difficulty: 2 },
  { word: "morango", category: "comida", difficulty: 1 },
  { word: "laranja", category: "comida", difficulty: 1 },
  { word: "limao", category: "comida", difficulty: 1 },
  { word: "cenoura", category: "comida", difficulty: 1 },
  { word: "batata", category: "comida", difficulty: 1 },
  { word: "tomate", category: "comida", difficulty: 1 },
  { word: "cebola", category: "comida", difficulty: 1 },
  { word: "milho", category: "comida", difficulty: 1 },
  { word: "arroz", category: "comida", difficulty: 1 },
  { word: "feijao", category: "comida", difficulty: 1 },
  { word: "macarrao", category: "comida", difficulty: 2 },
  { word: "pipoca", category: "comida", difficulty: 1 },
  { word: "chocolate", category: "comida", difficulty: 1 },
  { word: "bala", category: "comida", difficulty: 1 },
  { word: "biscoito", category: "comida", difficulty: 1 },
  { word: "torta", category: "comida", difficulty: 1 },
  { word: "cafe", category: "comida", difficulty: 1 },
  { word: "leite", category: "comida", difficulty: 1 },
  { word: "suco", category: "comida", difficulty: 1 },
  { word: "sanduiche", category: "comida", difficulty: 1 },
  { word: "salada", category: "comida", difficulty: 1 },
  { word: "churrasco", category: "comida", difficulty: 2 },
  { word: "peixe-frito", category: "comida", difficulty: 2 },
  { word: "sushi", category: "comida", difficulty: 1 },
  { word: "pastel", category: "comida", difficulty: 1 },
  { word: "coxinha", category: "comida", difficulty: 2 },

  // profissoes
  { word: "medico", category: "profissao", difficulty: 1 },
  { word: "professor", category: "profissao", difficulty: 1 },
  { word: "bombeiro", category: "profissao", difficulty: 1 },
  { word: "policial", category: "profissao", difficulty: 1 },
  { word: "cozinheiro", category: "profissao", difficulty: 1 },
  { word: "pintor", category: "profissao", difficulty: 1 },
  { word: "musico", category: "profissao", difficulty: 1 },
  { word: "piloto", category: "profissao", difficulty: 1 },
  { word: "marinheiro", category: "profissao", difficulty: 2 },
  { word: "cientista", category: "profissao", difficulty: 2 },
  { word: "dentista", category: "profissao", difficulty: 1 },
  { word: "advogado", category: "profissao", difficulty: 2 },
  { word: "agricultor", category: "profissao", difficulty: 2 },
  { word: "pescador", category: "profissao", difficulty: 1 },
  { word: "astronauta", category: "profissao", difficulty: 2 },
  { word: "palhaco", category: "profissao", difficulty: 1 },
  { word: "mago", category: "profissao", difficulty: 1 },
  { word: "pirata", category: "profissao", difficulty: 1 },
  { word: "cavaleiro", category: "profissao", difficulty: 2 },
  { word: "rei", category: "profissao", difficulty: 1 },
  { word: "rainha", category: "profissao", difficulty: 1 },
  { word: "princesa", category: "profissao", difficulty: 1 },

  // lugares
  { word: "praia", category: "lugar", difficulty: 1 },
  { word: "montanha", category: "lugar", difficulty: 1 },
  { word: "floresta", category: "lugar", difficulty: 1 },
  { word: "deserto", category: "lugar", difficulty: 1 },
  { word: "castelo", category: "lugar", difficulty: 1 },
  { word: "escola", category: "lugar", difficulty: 1 },
  { word: "hospital", category: "lugar", difficulty: 1 },
  { word: "fazenda", category: "lugar", difficulty: 1 },
  { word: "cidade", category: "lugar", difficulty: 1 },
  { word: "ponte", category: "lugar", difficulty: 1 },
  { word: "vulcao", category: "lugar", difficulty: 2 },
  { word: "ilha", category: "lugar", difficulty: 1 },
  { word: "cachoeira", category: "lugar", difficulty: 2 },
  { word: "igreja", category: "lugar", difficulty: 1 },
  { word: "aeroporto", category: "lugar", difficulty: 2 },
  { word: "zoologico", category: "lugar", difficulty: 2 },
  { word: "parque", category: "lugar", difficulty: 1 },
  { word: "biblioteca", category: "lugar", difficulty: 2 },
  { word: "farol", category: "lugar", difficulty: 1 },
  { word: "iglu", category: "lugar", difficulty: 1 },

  // acoes/conceitos concretos
  { word: "correr", category: "acao", difficulty: 1 },
  { word: "nadar", category: "acao", difficulty: 1 },
  { word: "pular", category: "acao", difficulty: 1 },
  { word: "dancar", category: "acao", difficulty: 1 },
  { word: "cantar", category: "acao", difficulty: 1 },
  { word: "dormir", category: "acao", difficulty: 1 },
  { word: "chorar", category: "acao", difficulty: 1 },
  { word: "rir", category: "acao", difficulty: 1 },
  { word: "voar", category: "acao", difficulty: 1 },
  { word: "escalar", category: "acao", difficulty: 2 },
  { word: "pescar", category: "acao", difficulty: 1 },
  { word: "cozinhar", category: "acao", difficulty: 1 },
  { word: "escrever", category: "acao", difficulty: 1 },
  { word: "desenhar", category: "acao", difficulty: 1 },
  { word: "lutar", category: "acao", difficulty: 1 },

  // veiculos
  { word: "carro", category: "objeto", difficulty: 1 },
  { word: "moto", category: "objeto", difficulty: 1 },
  { word: "bicicleta", category: "objeto", difficulty: 1 },
  { word: "aviao", category: "objeto", difficulty: 1 },
  { word: "navio", category: "objeto", difficulty: 1 },
  { word: "barco", category: "objeto", difficulty: 1 },
  { word: "trem", category: "objeto", difficulty: 1 },
  { word: "onibus", category: "objeto", difficulty: 1 },
  { word: "caminhao", category: "objeto", difficulty: 1 },
  { word: "helicoptero", category: "objeto", difficulty: 2 },
  { word: "foguete", category: "objeto", difficulty: 1 },
  { word: "submarino", category: "objeto", difficulty: 2 },
  { word: "trator", category: "objeto", difficulty: 1 },
  { word: "skate", category: "objeto", difficulty: 1 },

  // natureza/clima
  { word: "sol", category: "natureza", difficulty: 1 },
  { word: "lua", category: "natureza", difficulty: 1 },
  { word: "estrela", category: "natureza", difficulty: 1 },
  { word: "nuvem", category: "natureza", difficulty: 1 },
  { word: "chuva", category: "natureza", difficulty: 1 },
  { word: "arco-iris", category: "natureza", difficulty: 2 },
  { word: "neve", category: "natureza", difficulty: 1 },
  { word: "raio", category: "natureza", difficulty: 1 },
  { word: "fogo", category: "natureza", difficulty: 1 },
  { word: "arvore", category: "natureza", difficulty: 1 },
  { word: "flor", category: "natureza", difficulty: 1 },
  { word: "folha", category: "natureza", difficulty: 1 },
  { word: "cacto", category: "natureza", difficulty: 1 },
  { word: "cogumelo", category: "natureza", difficulty: 1 },
  { word: "rio", category: "natureza", difficulty: 1 },
  { word: "mar", category: "natureza", difficulty: 1 },
  { word: "lago", category: "natureza", difficulty: 1 },
];

export function pickWordOptions(usedWords: Set<string>, count = 3): WordEntry[] {
  const available = DRAW_WORDS.filter((w) => !usedWords.has(w.word));
  const pool = available.length >= count ? available : DRAW_WORDS;
  const picked: WordEntry[] = [];
  const indices = new Set<number>();
  while (picked.length < count && picked.length < pool.length) {
    const idx = Math.floor(Math.random() * pool.length);
    if (indices.has(idx)) continue;
    indices.add(idx);
    picked.push(pool[idx]);
  }
  return picked;
}
