// Banco principal da Corrida do Conhecimento: perguntas autorais, escritas para o jogo.
// Formato compacto: [dificuldade, pergunta, resposta certa, [3 erradas]].
// A ordem das alternativas nao importa: o servidor embaralha a cada partida (withShuffledOptions).
// Ids sao gerados pela posicao (his-101, his-102...), entao so acrescente no FIM de cada lista.

import type { RaceCategory, RaceDifficulty, RaceQuestion } from "./raceQuestions";

type Row = [RaceDifficulty, string, string, [string, string, string]];

function bank(category: RaceCategory, prefix: string, rows: Row[]): RaceQuestion[] {
  return rows.map(([difficulty, question, right, wrong], i) => ({
    id: `${prefix}-${101 + i}`,
    question,
    options: [right, ...wrong],
    correctIndex: 0,
    category,
    difficulty,
  }));
}

const historia = bank("historia", "his", [
  [1, "Quem comandava a esquadra portuguesa que chegou ao Brasil em 1500?", "Pedro Álvares Cabral", ["Vasco da Gama", "Cristóvão Colombo", "Fernão de Magalhães"]],
  [1, "Qual foi a primeira capital do Brasil?", "Salvador", ["Rio de Janeiro", "Recife", "São Paulo"]],
  [1, "Em que ano Brasília foi inaugurada?", "1960", ["1950", "1964", "1970"]],
  [1, "Quem foi o primeiro presidente dos Estados Unidos?", "George Washington", ["Abraham Lincoln", "Thomas Jefferson", "John Adams"]],
  [1, "Em que ano Cristóvão Colombo chegou à América?", "1492", ["1500", "1453", "1519"]],
  [1, "Em que ano terminou a Segunda Guerra Mundial?", "1945", ["1918", "1939", "1950"]],
  [1, "Qual líder da Inconfidência Mineira foi enforcado em 1792?", "Tiradentes", ["Cláudio Manuel da Costa", "Tomás Antônio Gonzaga", "Joaquim Silvério dos Reis"]],
  [1, "Qual povo antigo construiu as pirâmides de Gizé?", "Egípcios", ["Romanos", "Gregos", "Persas"]],
  [1, "Quem assinou a Lei Áurea?", "Princesa Isabel", ["Imperatriz Leopoldina", "Carlota Joaquina", "Dona Maria I"]],
  [1, "Quem foi o primeiro homem a pisar na Lua?", "Neil Armstrong", ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins"]],
  [1, "Qual navio afundou em 1912 depois de bater em um iceberg?", "Titanic", ["Lusitania", "Britannic", "Queen Mary"]],
  [1, "Qual líder da independência da Índia ficou famoso pela resistência não violenta?", "Mahatma Gandhi", ["Jawaharlal Nehru", "Nelson Mandela", "Martin Luther King Jr."]],
  [1, "Quem foi o primeiro presidente negro da África do Sul?", "Nelson Mandela", ["Desmond Tutu", "Kofi Annan", "Thabo Mbeki"]],
  [1, "Quem fez o famoso discurso \"Eu tenho um sonho\", em 1963?", "Martin Luther King Jr.", ["Malcolm X", "Barack Obama", "Nelson Mandela"]],
  [1, "Qual rainha governou o Reino Unido por mais de 70 anos, até 2022?", "Elizabeth II", ["Vitória", "Maria I", "Ana"]],
  [2, "Em que ano o ser humano pisou na Lua pela primeira vez?", "1969", ["1965", "1972", "1961"]],
  [2, "Qual cidade romana foi soterrada pela erupção do Vesúvio em 79 d.C.?", "Pompeia", ["Atenas", "Cartago", "Troia"]],
  [2, "Qual imperador francês foi derrotado na Batalha de Waterloo?", "Napoleão Bonaparte", ["Luís XVI", "Carlos Magno", "Napoleão III"]],
  [2, "Qual presidente brasileiro criou a CLT, em 1943?", "Getúlio Vargas", ["Juscelino Kubitschek", "Eurico Gaspar Dutra", "Jânio Quadros"]],
  [2, "Qual presidente brasileiro mandou construir Brasília?", "Juscelino Kubitschek", ["Getúlio Vargas", "Jânio Quadros", "Castelo Branco"]],
  [2, "Em que ano começou a Primeira Guerra Mundial?", "1914", ["1905", "1918", "1939"]],
  [2, "Em que ano começou a ditadura militar no Brasil?", "1964", ["1954", "1968", "1970"]],
  [2, "Qual tratado de 1494 dividiu as terras descobertas entre Portugal e Espanha?", "Tratado de Tordesilhas", ["Tratado de Madri", "Tratado de Versalhes", "Tratado de Utrecht"]],
  [2, "Por que a família real portuguesa veio para o Brasil em 1808?", "Para fugir das tropas de Napoleão", ["Para explorar o ouro de Minas", "Por causa de uma guerra com a Espanha", "Para abolir a escravidão"]],
  [2, "Qual cidade-estado grega é considerada o berço da democracia?", "Atenas", ["Esparta", "Tebas", "Corinto"]],
  [2, "Quem foi o primeiro ser humano a viajar ao espaço?", "Yuri Gagarin", ["Neil Armstrong", "John Glenn", "Alan Shepard"]],
  [2, "Como ficou conhecida a disputa entre Estados Unidos e União Soviética após 1945, sem confronto direto entre os dois?", "Guerra Fria", ["Guerra dos Cem Anos", "Guerra do Golfo", "Guerra da Coreia"]],
  [2, "Qual guerra do século XIX opôs Brasil, Argentina e Uruguai a um país vizinho?", "Guerra do Paraguai", ["Guerra dos Farrapos", "Guerra de Canudos", "Guerra do Contestado"]],
  [2, "Qual revolta gaúcha durou de 1835 a 1845?", "Revolução Farroupilha", ["Balaiada", "Cabanagem", "Sabinada"]],
  [2, "Quem liderou o arraial de Canudos, no sertão da Bahia?", "Antônio Conselheiro", ["Lampião", "Padre Cícero", "Zumbi dos Palmares"]],
  [2, "Qual líder quilombola é homenageado no Dia da Consciência Negra, 20 de novembro?", "Zumbi dos Palmares", ["João Cândido", "Luís Gama", "André Rebouças"]],
  [2, "Quem foi o último imperador do Brasil?", "Dom Pedro II", ["Dom Pedro I", "Dom João VI", "Dom Miguel"]],
  [2, "Em que ano foi promulgada a atual Constituição brasileira?", "1988", ["1985", "1946", "1967"]],
  [2, "Qual império foi fundado por Gengis Khan?", "Império Mongol", ["Império Otomano", "Império Persa", "Império Bizantino"]],
  [2, "Qual presidente brasileiro deixou o cargo em 1992, durante um processo de impeachment?", "Fernando Collor", ["José Sarney", "Itamar Franco", "Fernando Henrique Cardoso"]],
  [2, "Em que ano o real passou a ser a moeda do Brasil?", "1994", ["1986", "1990", "2000"]],
  [2, "Segundo a lenda, qual imperador romano tocava lira enquanto Roma pegava fogo?", "Nero", ["Calígula", "Augusto", "Trajano"]],
  [2, "Qual país lançou o Sputnik, primeiro satélite artificial, em 1957?", "União Soviética", ["Estados Unidos", "Alemanha", "China"]],
  [2, "Qual navegador português chegou à Índia por mar em 1498?", "Vasco da Gama", ["Pedro Álvares Cabral", "Bartolomeu Dias", "Fernão de Magalhães"]],
  [2, "Qual cidade japonesa foi atingida pela primeira bomba atômica, em 1945?", "Hiroshima", ["Nagasaki", "Tóquio", "Osaka"]],
  [2, "Quem liderou a Revolução Cubana ao lado de Che Guevara?", "Fidel Castro", ["Hugo Chávez", "Salvador Allende", "Juan Perón"]],
  [3, "Qual faraó teve a tumba encontrada quase intacta em 1922?", "Tutancâmon", ["Ramsés II", "Quéops", "Akhenaton"]],
  [3, "Em que ano Constantinopla foi conquistada pelos otomanos?", "1453", ["1492", "1204", "1517"]],
  [3, "Qual documento de 1215 limitou os poderes do rei da Inglaterra?", "Magna Carta", ["Bill of Rights", "Tratado de Paris", "Édito de Nantes"]],
  [3, "Quem comandou a expedição que iniciou, em 1519, a primeira volta ao mundo?", "Fernão de Magalhães", ["Vasco da Gama", "Cristóvão Colombo", "Américo Vespúcio"]],
  [3, "Qual povo fundou Tenochtitlán, onde hoje fica a Cidade do México?", "Astecas", ["Maias", "Incas", "Olmecas"]],
  [3, "Qual presidente brasileiro renunciou em 1961, depois de apenas sete meses no cargo?", "Jânio Quadros", ["João Goulart", "Café Filho", "Juscelino Kubitschek"]],
  [3, "Quem foi o primeiro presidente civil a tomar posse após a ditadura militar, em 1985?", "José Sarney", ["Tancredo Neves", "Fernando Collor", "Ulysses Guimarães"]],
  [3, "Como ficou conhecida a crise econômica que começou com a quebra da Bolsa de Nova York em 1929?", "Grande Depressão", ["New Deal", "Plano Marshall", "Crise do Petróleo"]],
  [3, "Qual era o nome do movimento de 1789 em Minas Gerais contra a cobrança de impostos pela Coroa?", "Inconfidência Mineira", ["Conjuração Baiana", "Revolta da Vacina", "Guerra dos Emboabas"]],
  [3, "Qual revolta de 1904, no Rio de Janeiro, foi contra a vacinação obrigatória?", "Revolta da Vacina", ["Revolta da Chibata", "Revolta dos Malês", "Revolta Armada"]],
]);

const geografia = bank("geografia", "geo", [
  [1, "Qual é o maior país do mundo em área?", "Rússia", ["Canadá", "China", "Estados Unidos"]],
  [1, "Qual é a capital da França?", "Paris", ["Lyon", "Marselha", "Nice"]],
  [1, "Qual é a capital da Argentina?", "Buenos Aires", ["Córdoba", "Rosário", "Montevidéu"]],
  [1, "Em qual continente fica o Egito?", "África", ["Ásia", "Europa", "Oceania"]],
  [1, "Qual é o rio com maior volume de água do mundo?", "Amazonas", ["Nilo", "Mississippi", "Yangtzé"]],
  [1, "Quantos estados tem o Brasil, sem contar o Distrito Federal?", "26", ["27", "25", "24"]],
  [1, "Qual é a capital de Portugal?", "Lisboa", ["Porto", "Coimbra", "Braga"]],
  [1, "Qual é a capital da Itália?", "Roma", ["Milão", "Veneza", "Florença"]],
  [1, "Qual é a capital do Rio Grande do Sul?", "Porto Alegre", ["Caxias do Sul", "Pelotas", "Florianópolis"]],
  [1, "Qual é a capital de Minas Gerais?", "Belo Horizonte", ["Ouro Preto", "Uberlândia", "Juiz de Fora"]],
  [1, "Qual é o menor país do mundo?", "Vaticano", ["Mônaco", "San Marino", "Liechtenstein"]],
  [1, "Quais cataratas ficam na fronteira entre Brasil e Argentina?", "Cataratas do Iguaçu", ["Cataratas do Niágara", "Cataratas Vitória", "Salto Ángel"]],
  [1, "Qual é o continente mais populoso?", "Ásia", ["África", "Europa", "América"]],
  [1, "Qual é a capital da Alemanha?", "Berlim", ["Munique", "Frankfurt", "Hamburgo"]],
  [1, "De qual estado brasileiro Florianópolis é a capital?", "Santa Catarina", ["Paraná", "Rio Grande do Sul", "Espírito Santo"]],
  [1, "Qual é o maior bioma brasileiro?", "Amazônia", ["Cerrado", "Mata Atlântica", "Caatinga"]],
  [1, "Qual rio do Nordeste é chamado de \"Velho Chico\"?", "Rio São Francisco", ["Rio Parnaíba", "Rio Tocantins", "Rio Jaguaribe"]],
  [1, "Qual linha imaginária divide a Terra em hemisfério norte e hemisfério sul?", "Linha do Equador", ["Meridiano de Greenwich", "Trópico de Capricórnio", "Trópico de Câncer"]],
  [1, "Qual cordilheira atravessa a América do Sul de norte a sul?", "Andes", ["Alpes", "Himalaia", "Montanhas Rochosas"]],
  [1, "Em qual país fica o Taj Mahal?", "Índia", ["Paquistão", "Nepal", "Bangladesh"]],
  [1, "Qual é a capital da Rússia?", "Moscou", ["São Petersburgo", "Kiev", "Minsk"]],
  [1, "Qual é a capital da China?", "Pequim", ["Xangai", "Hong Kong", "Cantão"]],
  [1, "Qual é a cidade mais populosa do Brasil?", "São Paulo", ["Rio de Janeiro", "Brasília", "Salvador"]],
  [1, "Qual país é conhecido como \"Terra do Sol Nascente\"?", "Japão", ["China", "Coreia do Sul", "Tailândia"]],
  [2, "Qual é o maior deserto quente do mundo?", "Saara", ["Atacama", "Gobi", "Kalahari"]],
  [2, "Em qual estado fica a Chapada Diamantina?", "Bahia", ["Minas Gerais", "Goiás", "Mato Grosso"]],
  [2, "Qual é a capital do Egito?", "Cairo", ["Alexandria", "Luxor", "Gizé"]],
  [2, "Qual é a capital do Tocantins?", "Palmas", ["Araguaína", "Gurupi", "Porto Nacional"]],
  [2, "Qual é a capital do Acre?", "Rio Branco", ["Porto Velho", "Boa Vista", "Cruzeiro do Sul"]],
  [2, "Qual é o ponto mais alto do Brasil?", "Pico da Neblina", ["Pico da Bandeira", "Monte Roraima", "Pico das Agulhas Negras"]],
  [2, "Quais dois países da América do Sul não fazem fronteira com o Brasil?", "Chile e Equador", ["Chile e Peru", "Equador e Uruguai", "Paraguai e Chile"]],
  [2, "Qual trópico passa pela cidade de São Paulo?", "Trópico de Capricórnio", ["Trópico de Câncer", "Linha do Equador", "Círculo Polar Antártico"]],
  [2, "Em qual país fica a Grande Barreira de Corais?", "Austrália", ["Indonésia", "Filipinas", "Nova Zelândia"]],
  [2, "Qual estreito separa a Europa da África?", "Estreito de Gibraltar", ["Estreito de Bósforo", "Estreito de Magalhães", "Estreito de Bering"]],
  [2, "Qual é o menor estado brasileiro em área?", "Sergipe", ["Alagoas", "Rio de Janeiro", "Espírito Santo"]],
  [2, "O arquipélago de Fernando de Noronha pertence a qual estado?", "Pernambuco", ["Rio Grande do Norte", "Paraíba", "Ceará"]],
  [2, "Qual é a capital da Coreia do Sul?", "Seul", ["Busan", "Pyongyang", "Incheon"]],
  [2, "Qual mar fica entre o sul da Europa e o norte da África?", "Mar Mediterrâneo", ["Mar Negro", "Mar do Norte", "Mar Vermelho"]],
  [2, "Qual é a maior planície alagável do mundo, localizada no Brasil?", "Pantanal", ["Pampa", "Cerrado", "Caatinga"]],
  [2, "Qual é a capital do Chile?", "Santiago", ["Valparaíso", "Lima", "La Paz"]],
  [3, "Qual é a capital da Turquia?", "Ancara", ["Istambul", "Esmirna", "Antália"]],
  [3, "Qual é a capital da Suíça?", "Berna", ["Zurique", "Genebra", "Basileia"]],
  [3, "Qual é a capital do Marrocos?", "Rabat", ["Casablanca", "Marrakech", "Fez"]],
  [3, "Qual é a capital da Nova Zelândia?", "Wellington", ["Auckland", "Christchurch", "Queenstown"]],
  [3, "Qual é a capital de Roraima?", "Boa Vista", ["Macapá", "Porto Velho", "Rio Branco"]],
  [3, "Qual bioma existe somente no Brasil?", "Caatinga", ["Pantanal", "Cerrado", "Pampa"]],
  [3, "Com quantos países o Brasil faz fronteira, contando a França pela Guiana Francesa?", "10", ["9", "11", "12"]],
  [3, "Qual é o maior país da África em área?", "Argélia", ["República Democrática do Congo", "Sudão", "Líbia"]],
  [3, "Em qual país fica o monte Kilimanjaro?", "Tanzânia", ["Quênia", "Etiópia", "Uganda"]],
  [3, "Qual é o rio mais longo da Europa?", "Volga", ["Danúbio", "Reno", "Sena"]],
  [3, "Qual é a capital da Islândia?", "Reykjavík", ["Oslo", "Helsinque", "Copenhague"]],
  [3, "Qual é a capital do Amapá?", "Macapá", ["Oiapoque", "Santana", "Belém"]],
]);

const ciencias = bank("ciencias", "cie", [
  [1, "Qual é a fórmula química da água?", "H₂O", ["CO₂", "O₂", "H₂O₂"]],
  [1, "Qual órgão bombeia o sangue pelo corpo?", "Coração", ["Pulmão", "Fígado", "Rim"]],
  [1, "Qual é a estrela mais próxima da Terra?", "Sol", ["Proxima Centauri", "Sirius", "Alfa Centauri"]],
  [1, "Quantos planetas existem no Sistema Solar?", "8", ["9", "7", "10"]],
  [1, "A baleia pertence a qual grupo de animais?", "Mamíferos", ["Peixes", "Anfíbios", "Répteis"]],
  [1, "Qual planeta fica mais perto do Sol?", "Mercúrio", ["Vênus", "Marte", "Terra"]],
  [1, "A que temperatura a água pura congela ao nível do mar?", "0 °C", ["10 °C", "-10 °C", "4 °C"]],
  [1, "Quais órgãos filtram o sangue e produzem a urina?", "Rins", ["Fígado", "Baço", "Pâncreas"]],
  [1, "Como se chama o processo em que as plantas produzem o próprio alimento usando a luz?", "Fotossíntese", ["Respiração", "Transpiração", "Germinação"]],
  [1, "Qual destes animais é um anfíbio?", "Sapo", ["Jacaré", "Tartaruga", "Lagarto"]],
  [1, "Qual planeta tem os anéis mais visíveis?", "Saturno", ["Júpiter", "Urano", "Netuno"]],
  [1, "Qual cientista formulou a teoria da relatividade?", "Albert Einstein", ["Isaac Newton", "Galileu Galilei", "Stephen Hawking"]],
  [1, "Qual cientista é associado à história da maçã e à lei da gravitação universal?", "Isaac Newton", ["Albert Einstein", "Galileu Galilei", "Nicolau Copérnico"]],
  [1, "Qual partícula do átomo tem carga elétrica negativa?", "Elétron", ["Próton", "Nêutron", "Núcleo"]],
  [1, "Qual molécula guarda a informação genética dos seres vivos?", "DNA", ["ATP", "Glicose", "Colágeno"]],
  [1, "Quanto tempo a Terra leva, aproximadamente, para dar uma volta completa em torno do Sol?", "365 dias", ["24 horas", "30 dias", "12 anos"]],
  [1, "Como se chama o movimento da Terra girando em torno do próprio eixo?", "Rotação", ["Translação", "Revolução", "Precessão"]],
  [1, "Qual mosquito transmite a dengue?", "Aedes aegypti", ["Anopheles", "Barbeiro", "Mosca tsé-tsé"]],
  [1, "Como se chama a galáxia onde fica o Sistema Solar?", "Via Láctea", ["Andrômeda", "Triângulo", "Sombreiro"]],
  [2, "Qual é o maior órgão do corpo humano?", "Pele", ["Fígado", "Intestino", "Cérebro"]],
  [2, "Quantos dentes tem um adulto com a dentição permanente completa?", "32", ["28", "30", "36"]],
  [2, "Qual vitamina o corpo produz quando a pele recebe luz do sol?", "Vitamina D", ["Vitamina C", "Vitamina A", "Vitamina B12"]],
  [2, "Qual é o símbolo químico do sódio?", "Na", ["S", "So", "Sd"]],
  [2, "Qual é o símbolo químico do ferro?", "Fe", ["F", "Fr", "Ir"]],
  [2, "Quem propôs a teoria da evolução por seleção natural?", "Charles Darwin", ["Jean-Baptiste Lamarck", "Gregor Mendel", "Louis Pasteur"]],
  [2, "Quem descobriu a penicilina?", "Alexander Fleming", ["Louis Pasteur", "Robert Koch", "Edward Jenner"]],
  [2, "Qual é a velocidade aproximada da luz no vácuo?", "300 mil km/s", ["30 mil km/s", "3 milhões de km/s", "300 km/s"]],
  [2, "Qual camada da atmosfera filtra boa parte da radiação ultravioleta do Sol?", "Camada de ozônio", ["Troposfera", "Ionosfera", "Exosfera"]],
  [2, "Qual é o pH da água pura a 25 °C?", "7", ["0", "14", "1"]],
  [2, "Qual tipo sanguíneo é conhecido como doador universal?", "O negativo", ["AB positivo", "A positivo", "B negativo"]],
  [2, "Quantas cavidades tem o coração humano?", "4", ["2", "3", "5"]],
  [2, "Qual é o maior osso do corpo humano?", "Fêmur", ["Tíbia", "Úmero", "Fíbula"]],
  [2, "Qual metal é líquido à temperatura ambiente?", "Mercúrio", ["Chumbo", "Alumínio", "Estanho"]],
  [2, "Qual gás é o mais abundante na atmosfera da Terra?", "Nitrogênio", ["Oxigênio", "Gás carbônico", "Argônio"]],
  [2, "Como se chama a passagem da água do estado líquido para o gasoso?", "Vaporização", ["Fusão", "Condensação", "Solidificação"]],
  [2, "Qual cientista ganhou dois Prêmios Nobel, em Física e em Química?", "Marie Curie", ["Rosalind Franklin", "Lise Meitner", "Ada Lovelace"]],
  [2, "Em qual planeta fica a Grande Mancha Vermelha, uma tempestade gigante?", "Júpiter", ["Marte", "Saturno", "Netuno"]],
  [3, "Qual é o símbolo químico da prata?", "Ag", ["Pt", "Pr", "Au"]],
  [3, "Qual é o símbolo químico do potássio?", "K", ["P", "Po", "Pt"]],
  [3, "Qual é o planeta mais quente do Sistema Solar?", "Vênus", ["Mercúrio", "Marte", "Júpiter"]],
  [3, "Quem é considerado o pai da genética?", "Gregor Mendel", ["Charles Darwin", "James Watson", "Louis Pasteur"]],
  [3, "Qual é a unidade de medida de força no Sistema Internacional?", "Newton", ["Joule", "Watt", "Pascal"]],
  [3, "Qual é a unidade de medida de energia no Sistema Internacional?", "Joule", ["Watt", "Newton", "Volt"]],
  [3, "Em que parte do sistema digestório acontece a maior parte da absorção dos nutrientes?", "Intestino delgado", ["Estômago", "Intestino grosso", "Esôfago"]],
  [3, "Quem descreveu, em 1909, a doença transmitida pelo inseto barbeiro?", "Carlos Chagas", ["Oswaldo Cruz", "Vital Brazil", "Adolfo Lutz"]],
  [3, "Qual organela das células vegetais realiza a fotossíntese?", "Cloroplasto", ["Mitocôndria", "Ribossomo", "Vacúolo"]],
  [3, "Qual é o número atômico do hidrogênio?", "1", ["2", "0", "8"]],
]);

const matematica = bank("matematica", "mat", [
  [1, "Quanto é 9 × 6?", "54", ["56", "48", "63"]],
  [1, "Quanto é 144 ÷ 12?", "12", ["11", "14", "13"]],
  [1, "Quanto é 25% de 80?", "20", ["25", "16", "40"]],
  [1, "Quantos minutos há em 3 horas?", "180", ["120", "300", "160"]],
  [1, "Quantos segundos tem uma hora?", "3.600", ["360", "6.000", "60"]],
  [1, "Quantos lados tem um octógono?", "8", ["6", "10", "12"]],
  [1, "Quantos graus mede um ângulo reto?", "90°", ["45°", "180°", "360°"]],
  [1, "Qual é o valor aproximado de π (pi)?", "3,14", ["2,71", "1,61", "3,41"]],
  [1, "Qual é o próximo número da sequência 2, 4, 8, 16...?", "32", ["24", "20", "30"]],
  [1, "Qual é a área de um quadrado com 7 cm de lado?", "49 cm²", ["28 cm²", "14 cm²", "42 cm²"]],
  [1, "Qual número romano representa 50?", "L", ["C", "D", "X"]],
  [1, "Quantos zeros tem o número um milhão?", "6", ["5", "7", "9"]],
  [1, "Quanto é 100 − 37?", "63", ["73", "67", "53"]],
  [1, "Como se chama o triângulo que tem os três lados iguais?", "Equilátero", ["Isósceles", "Escaleno", "Retângulo"]],
  [1, "Qual é a média de 4, 8 e 12?", "8", ["12", "6", "24"]],
  [1, "Quantos metros tem 1 quilômetro?", "1.000", ["100", "10.000", "10"]],
  [1, "Qual é a chance de sair \"cara\" ao jogar uma moeda honesta?", "50%", ["25%", "33%", "100%"]],
  [2, "Quanto é 3² + 4²?", "25", ["49", "14", "12"]],
  [2, "Quanto é 1/2 + 1/4?", "3/4", ["2/6", "1/8", "2/4"]],
  [2, "Qual é o próximo número da sequência 1, 1, 2, 3, 5, 8...?", "13", ["11", "12", "16"]],
  [2, "Quanto é 0,5 × 0,5?", "0,25", ["1", "0,1", "2,5"]],
  [2, "Um produto de R$ 200 tem 30% de desconto. Quanto passa a custar?", "R$ 140", ["R$ 170", "R$ 160", "R$ 130"]],
  [2, "Qual é a raiz cúbica de 27?", "3", ["9", "6", "13"]],
  [2, "Quantos vértices tem um cubo?", "8", ["6", "12", "4"]],
  [2, "Qual é o perímetro de um retângulo de 5 cm por 3 cm?", "16 cm", ["15 cm", "8 cm", "30 cm"]],
  [2, "Quanto é (−3) × (−4)?", "12", ["−12", "7", "−7"]],
  [2, "Quantos zeros tem o número um bilhão?", "9", ["6", "12", "10"]],
  [2, "Qual é o MMC de 4 e 6?", "12", ["24", "2", "10"]],
  [2, "Qual é o MDC de 18 e 24?", "6", ["3", "12", "2"]],
  [2, "Quanto é 15 + 15 × 2?", "45", ["60", "30", "50"]],
  [2, "Qual é a metade de 3/4?", "3/8", ["3/2", "1/4", "6/8"]],
  [2, "Quanto é 2⁰ (dois elevado a zero)?", "1", ["0", "2", "Não existe"]],
  [2, "Como se chama o polígono de 10 lados?", "Decágono", ["Dodecágono", "Eneágono", "Undecágono"]],
  [2, "Quanto vale a soma dos ângulos internos de um quadrilátero?", "360°", ["180°", "270°", "540°"]],
  [2, "Quanto é 13²?", "169", ["156", "196", "139"]],
  [2, "Um carro anda a 60 km/h. Quantos km percorre em 2 horas e 30 minutos?", "150 km", ["120 km", "180 km", "130 km"]],
  [2, "Qual é a chance de tirar 6 ao jogar um dado comum?", "1/6", ["1/3", "1/2", "1/12"]],
  [2, "Qual é o único número primo par?", "2", ["4", "0", "6"]],
  [3, "Quanto é 10% de 10% de 1.000?", "10", ["100", "1", "20"]],
  [3, "Quanto é 7³?", "343", ["21", "49", "294"]],
  [3, "Quantas arestas tem um cubo?", "12", ["8", "6", "10"]],
  [3, "Qual ano o número romano MCMXC representa?", "1990", ["1910", "2010", "1490"]],
  [3, "Em um triângulo retângulo com catetos de 6 e 8, quanto mede a hipotenusa?", "10", ["14", "12", "48"]],
  [3, "Quanto é 5! (cinco fatorial)?", "120", ["25", "60", "720"]],
  [3, "Quantos números primos existem entre 1 e 10?", "4", ["3", "5", "6"]],
  [3, "Quanto é 1.000 ÷ 8?", "125", ["120", "128", "100"]],
  [3, "Qual é o logaritmo de 1.000 na base 10?", "3", ["10", "100", "4"]],
  [3, "Quanto mede cada ângulo interno de um hexágono regular?", "120°", ["60°", "90°", "135°"]],
]);

const tecnologia = bank("tecnologia", "tec", [
  [1, "Qual empresa criou o sistema operacional Windows?", "Microsoft", ["Apple", "IBM", "Google"]],
  [1, "Qual empresa fabrica o iPhone?", "Apple", ["Samsung", "Motorola", "Nokia"]],
  [1, "Quem fundou a Microsoft ao lado de Paul Allen?", "Bill Gates", ["Steve Jobs", "Mark Zuckerberg", "Larry Page"]],
  [1, "Quem fundou a Apple ao lado de Steve Wozniak?", "Steve Jobs", ["Bill Gates", "Elon Musk", "Jeff Bezos"]],
  [1, "Quem criou o Facebook?", "Mark Zuckerberg", ["Jack Dorsey", "Larry Page", "Bill Gates"]],
  [1, "O que significa a sigla \"www\" nos endereços da internet?", "World Wide Web", ["Wide Web World", "Web World Wide", "World Web Window"]],
  [1, "Qual destas é uma extensão comum de arquivo de imagem?", ".jpg", [".txt", ".exe", ".mp3"]],
  [1, "Qual linguagem define as cores, fontes e o layout de páginas web?", "CSS", ["HTML", "SQL", "Python"]],
  [1, "Qual empresa desenvolve o sistema Android?", "Google", ["Apple", "Samsung", "Microsoft"]],
  [1, "Qual destes é um periférico de entrada?", "Teclado", ["Monitor", "Impressora", "Caixa de som"]],
  [1, "Qual empresa criou o videogame PlayStation?", "Sony", ["Nintendo", "Microsoft", "Sega"]],
  [1, "Qual empresa criou o personagem Mario?", "Nintendo", ["Sega", "Sony", "Atari"]],
  [1, "Qual jogo de construção com blocos, lançado oficialmente em 2011, virou um dos mais vendidos da história?", "Minecraft", ["Roblox", "Fortnite", "Terraria"]],
  [1, "No Windows, qual atalho copia o que está selecionado?", "Ctrl + C", ["Ctrl + V", "Ctrl + X", "Ctrl + Z"]],
  [1, "Qual atalho desfaz a última ação na maioria dos programas?", "Ctrl + Z", ["Ctrl + Y", "Ctrl + A", "Ctrl + S"]],
  [1, "Qual rede social teve um passarinho azul como símbolo até 2023?", "Twitter", ["Facebook", "Instagram", "LinkedIn"]],
  [1, "O que é um \"bug\" em programação?", "Um erro no programa", ["Um tipo de vírus", "Um cabo de rede", "Uma cópia de segurança"]],
  [1, "Qual empresa criou o navegador Chrome?", "Google", ["Microsoft", "Mozilla", "Apple"]],
  [1, "Qual destas unidades de armazenamento é a maior?", "Terabyte", ["Gigabyte", "Megabyte", "Kilobyte"]],
  [2, "O que significa a sigla USB?", "Universal Serial Bus", ["Unidade de Sistema Básico", "User System Board", "Universal Storage Box"]],
  [2, "Qual linguagem é usada para consultar bancos de dados relacionais?", "SQL", ["HTML", "CSS", "Markdown"]],
  [2, "Qual linguagem de programação ganhou o nome por causa do grupo de humor Monty Python?", "Python", ["Ruby", "Java", "Perl"]],
  [2, "Quem é considerada a primeira programadora da história?", "Ada Lovelace", ["Grace Hopper", "Marie Curie", "Hedy Lamarr"]],
  [2, "Qual matemático britânico é considerado um dos pais da computação e ajudou a decifrar códigos nazistas?", "Alan Turing", ["Charles Babbage", "John von Neumann", "Claude Shannon"]],
  [2, "Qual sistema operacional de código aberto foi criado por Linus Torvalds?", "Linux", ["Unix", "MS-DOS", "Solaris"]],
  [2, "Em computação, tradicionalmente, 1 kilobyte equivale a quantos bytes?", "1.024", ["1.000", "100", "512"]],
  [2, "O que é phishing?", "Golpe que se passa por alguém confiável para roubar dados", ["Vírus que apaga o disco rígido", "Técnica de cópia de segurança", "Protocolo de rede sem fio"]],
  [2, "Qual protocolo indica que a conexão com um site é criptografada (o cadeado no navegador)?", "HTTPS", ["HTTP", "FTP", "SMTP"]],
  [2, "Qual destes componentes mantém os arquivos guardados mesmo com o computador desligado?", "SSD", ["Memória RAM", "Memória cache", "Registrador da CPU"]],
  [2, "Qual é a base do sistema hexadecimal?", "16", ["8", "10", "2"]],
  [2, "O que significa a sigla GPS?", "Global Positioning System", ["General Position Satellite", "Global Phone Service", "Geo Path System"]],
  [2, "Em que ano foi lançado o primeiro iPhone?", "2007", ["2005", "2010", "2003"]],
  [2, "Quem fundou a Amazon?", "Jeff Bezos", ["Elon Musk", "Bill Gates", "Larry Ellison"]],
  [2, "O que é software de código aberto?", "Programa com o código-fonte disponível para ver e modificar", ["Programa que só funciona conectado à internet", "Programa gratuito por 30 dias", "Programa sem senha de acesso"]],
  [3, "O que significa a sigla PDF?", "Portable Document Format", ["Printable Data File", "Public Document File", "Personal Data Format"]],
  [3, "Em que década foi criada a linguagem JavaScript?", "Anos 1990", ["Anos 1970", "Anos 1980", "Anos 2000"]],
  [3, "Em qual país foi criado o jogo Tetris?", "União Soviética", ["Japão", "Estados Unidos", "Coreia do Sul"]],
  [3, "Qual era o nome original do buscador que virou o Google?", "BackRub", ["AltaVista", "PageRank", "Lycos"]],
  [3, "Quanto vale o número binário 1010 no sistema decimal?", "10", ["5", "12", "8"]],
  [3, "Qual sigla descreve um conjunto de regras para um programa conversar com outro?", "API", ["SDK", "IDE", "URL"]],
  [3, "Qual computador de 1946 é considerado um dos primeiros computadores eletrônicos de uso geral?", "ENIAC", ["UNIVAC", "Apple I", "IBM PC"]],
  [3, "Qual \"lei\" previu que o número de transistores em um chip dobraria a cada dois anos, aproximadamente?", "Lei de Moore", ["Lei de Murphy", "Lei de Ohm", "Lei de Newton"]],
  [3, "O que significa a sigla HTML?", "HyperText Markup Language", ["HighText Machine Language", "HyperTool Multi Language", "Home Text Markup Link"]],
]);

const arteCultura = bank("arte-cultura", "art", [
  [1, "Quem pintou \"A Noite Estrelada\"?", "Vincent van Gogh", ["Claude Monet", "Pablo Picasso", "Salvador Dalí"]],
  [1, "Quem escreveu \"O Pequeno Príncipe\"?", "Antoine de Saint-Exupéry", ["Júlio Verne", "Victor Hugo", "Albert Camus"]],
  [1, "Quem criou o Sítio do Picapau Amarelo?", "Monteiro Lobato", ["Ziraldo", "Mauricio de Sousa", "Ruth Rocha"]],
  [1, "Quem criou a Turma da Mônica?", "Mauricio de Sousa", ["Ziraldo", "Monteiro Lobato", "Angeli"]],
  [1, "Quem escreveu a série \"Harry Potter\"?", "J. K. Rowling", ["J. R. R. Tolkien", "C. S. Lewis", "Rick Riordan"]],
  [1, "Quem escreveu \"O Senhor dos Anéis\"?", "J. R. R. Tolkien", ["C. S. Lewis", "George R. R. Martin", "J. K. Rowling"]],
  [1, "Qual cantor ficou conhecido como \"Rei do Rock\"?", "Elvis Presley", ["Chuck Berry", "Little Richard", "Michael Jackson"]],
  [1, "De qual banda britânica faziam parte John Lennon e Paul McCartney?", "The Beatles", ["The Rolling Stones", "Queen", "The Who"]],
  [1, "Quem era o vocalista da banda Queen?", "Freddie Mercury", ["Mick Jagger", "Bono", "Robert Plant"]],
  [1, "Qual cantor é chamado de \"Rei do Pop\"?", "Michael Jackson", ["Prince", "Elvis Presley", "Stevie Wonder"]],
  [1, "Qual expressão afro-brasileira mistura luta, dança e música, ao som do berimbau?", "Capoeira", ["Frevo", "Maracatu", "Samba de roda"]],
  [1, "Qual instrumento tem, normalmente, 88 teclas?", "Piano", ["Acordeão", "Cravo", "Xilofone"]],
  [1, "Quantas cordas tem um violão tradicional?", "6", ["4", "5", "7"]],
  [2, "Quem pintou o teto da Capela Sistina?", "Michelangelo", ["Rafael", "Leonardo da Vinci", "Donatello"]],
  [2, "Quem pintou \"Guernica\"?", "Pablo Picasso", ["Salvador Dalí", "Joan Miró", "Francisco de Goya"]],
  [2, "Qual artista pintou os relógios derretidos de \"A Persistência da Memória\"?", "Salvador Dalí", ["René Magritte", "Pablo Picasso", "Wassily Kandinsky"]],
  [2, "Quem escreveu \"Os Lusíadas\"?", "Luís de Camões", ["Fernando Pessoa", "Eça de Queirós", "Gil Vicente"]],
  [2, "Quem escreveu \"Grande Sertão: Veredas\"?", "Guimarães Rosa", ["Graciliano Ramos", "Jorge Amado", "Érico Veríssimo"]],
  [2, "Quem escreveu \"Vidas Secas\"?", "Graciliano Ramos", ["Rachel de Queiroz", "José Lins do Rego", "Jorge Amado"]],
  [2, "Quem escreveu \"Iracema\"?", "José de Alencar", ["Machado de Assis", "Castro Alves", "Gonçalves Dias"]],
  [2, "Quem escreveu \"Capitães da Areia\"?", "Jorge Amado", ["Graciliano Ramos", "Érico Veríssimo", "Rachel de Queiroz"]],
  [2, "Quem escreveu \"A Hora da Estrela\"?", "Clarice Lispector", ["Cecília Meireles", "Rachel de Queiroz", "Lygia Fagundes Telles"]],
  [2, "Quem escreveu \"O Auto da Compadecida\"?", "Ariano Suassuna", ["Nelson Rodrigues", "Dias Gomes", "João Cabral de Melo Neto"]],
  [2, "Qual poeta escreveu \"No meio do caminho tinha uma pedra\"?", "Carlos Drummond de Andrade", ["Manuel Bandeira", "Vinicius de Moraes", "Cecília Meireles"]],
  [2, "Quem criou o Menino Maluquinho?", "Ziraldo", ["Mauricio de Sousa", "Monteiro Lobato", "Ruth Rocha"]],
  [2, "Quem escreveu \"Dom Quixote\"?", "Miguel de Cervantes", ["William Shakespeare", "Dante Alighieri", "Luís de Camões"]],
  [2, "Quem escreveu \"A Divina Comédia\"?", "Dante Alighieri", ["Giovanni Boccaccio", "Nicolau Maquiavel", "Petrarca"]],
  [2, "Qual compositor austríaco compôs a ópera \"A Flauta Mágica\"?", "Wolfgang Amadeus Mozart", ["Ludwig van Beethoven", "Johann Sebastian Bach", "Joseph Haydn"]],
  [2, "Qual estilo musical brasileiro surgiu no fim dos anos 1950 com João Gilberto e Tom Jobim?", "Bossa nova", ["Tropicália", "Samba-enredo", "Jovem Guarda"]],
  [2, "Quem compôs \"Garota de Ipanema\" com Vinicius de Moraes?", "Tom Jobim", ["Chico Buarque", "Caetano Veloso", "Gilberto Gil"]],
  [2, "Qual cantor e sanfoneiro ficou conhecido como \"Rei do Baião\"?", "Luiz Gonzaga", ["Dominguinhos", "Gilberto Gil", "Jackson do Pandeiro"]],
  [2, "Em qual museu está exposta a Mona Lisa?", "Museu do Louvre", ["Museu do Prado", "Galeria Uffizi", "Museu Britânico"]],
  [2, "Em qual estado acontece o Festival de Parintins, com os bois Garantido e Caprichoso?", "Amazonas", ["Pará", "Maranhão", "Bahia"]],
  [2, "O frevo é uma dança típica de qual estado?", "Pernambuco", ["Bahia", "Ceará", "Paraíba"]],
  [2, "Qual filme brasileiro de 2002 mostra o crescimento do crime em uma favela do Rio?", "Cidade de Deus", ["Tropa de Elite", "Central do Brasil", "Carandiru"]],
  [2, "Qual personagem de Shakespeare diz \"Ser ou não ser, eis a questão\"?", "Hamlet", ["Macbeth", "Otelo", "Rei Lear"]],
  [2, "Quem escreveu \"Memórias Póstumas de Brás Cubas\"?", "Machado de Assis", ["José de Alencar", "Aluísio Azevedo", "Lima Barreto"]],
  [2, "Quantas cordas tem um violino?", "4", ["6", "5", "3"]],
  [3, "Quem escreveu \"O Cortiço\"?", "Aluísio Azevedo", ["Machado de Assis", "José de Alencar", "Lima Barreto"]],
  [3, "Qual cantora luso-brasileira ficou conhecida como \"A Pequena Notável\"?", "Carmen Miranda", ["Elis Regina", "Gal Costa", "Clara Nunes"]],
  [3, "Qual era o apelido de Antônio Francisco Lisboa, autor dos profetas de Congonhas?", "Aleijadinho", ["Mestre Valentim", "Mestre Ataíde", "Brecheret"]],
  [3, "Qual pintora modernista brasileira pintou o quadro \"Operários\" (1933)?", "Tarsila do Amaral", ["Anita Malfatti", "Djanira", "Lygia Clark"]],
  [3, "Quem pintou a série \"Retirantes\" (1944)?", "Candido Portinari", ["Di Cavalcanti", "Tarsila do Amaral", "Alfredo Volpi"]],
  [3, "Qual filme deu ao Brasil o primeiro Oscar de Melhor Filme Internacional, em 2025?", "Ainda Estou Aqui", ["Central do Brasil", "Cidade de Deus", "O Pagador de Promessas"]],
  [3, "Qual poeta português criou heterônimos como Alberto Caeiro e Ricardo Reis?", "Fernando Pessoa", ["Luís de Camões", "Florbela Espanca", "José Saramago"]],
  [3, "Qual escritor português ganhou o Prêmio Nobel de Literatura em 1998?", "José Saramago", ["Fernando Pessoa", "Eça de Queirós", "António Lobo Antunes"]],
  [3, "Qual pintor holandês pintou \"Moça com Brinco de Pérola\"?", "Johannes Vermeer", ["Rembrandt", "Vincent van Gogh", "Frans Hals"]],
]);

const esportes = bank("esportes", "esp", [
  [1, "Qual jogador é conhecido como \"Rei do Futebol\"?", "Pelé", ["Garrincha", "Zico", "Romário"]],
  [1, "Em que ano o Brasil conquistou o pentacampeonato mundial de futebol?", "2002", ["1994", "1998", "2006"]],
  [1, "Qual seleção venceu o Brasil por 7 a 1 na Copa de 2014?", "Alemanha", ["Argentina", "Holanda", "Espanha"]],
  [1, "Qual país sediou a Copa do Mundo de 2022?", "Catar", ["Rússia", "Arábia Saudita", "Emirados Árabes Unidos"]],
  [1, "Qual seleção venceu a Copa do Mundo de 2022?", "Argentina", ["França", "Croácia", "Marrocos"]],
  [1, "Quantos jogadores de cada time ficam em quadra no vôlei?", "6", ["5", "7", "4"]],
  [1, "Quantos jogadores de cada time ficam em quadra no basquete?", "5", ["6", "7", "4"]],
  [1, "Quanto dura o tempo regulamentar de uma partida de futebol?", "90 minutos", ["80 minutos", "100 minutos", "60 minutos"]],
  [1, "Em qual esporte o objetivo é colocar a bola no buraco com o menor número de tacadas?", "Golfe", ["Críquete", "Hóquei", "Polo"]],
  [1, "Qual esporte é disputado no torneio de Wimbledon?", "Tênis", ["Golfe", "Críquete", "Rúgbi"]],
  [1, "Qual nadador americano é o maior medalhista de ouro da história olímpica?", "Michael Phelps", ["Mark Spitz", "Ryan Lochte", "Caeleb Dressel"]],
  [1, "Qual velocista jamaicano correu os 100 metros em 9,58 segundos, em 2009?", "Usain Bolt", ["Yohan Blake", "Asafa Powell", "Tyson Gay"]],
  [1, "Quantos anéis tem o símbolo olímpico?", "5", ["4", "6", "7"]],
  [1, "Qual cidade sediou os Jogos Olímpicos de 2016?", "Rio de Janeiro", ["Londres", "Tóquio", "Pequim"]],
  [1, "Qual cidade sediou os Jogos Olímpicos de 2024?", "Paris", ["Los Angeles", "Tóquio", "Madri"]],
  [1, "Em qual esporte existe a jogada chamada \"home run\"?", "Beisebol", ["Críquete", "Rúgbi", "Hóquei"]],
  [1, "Em qual país surgiu o judô?", "Japão", ["China", "Coreia do Sul", "Tailândia"]],
  [1, "Qual clube brasileiro é chamado de \"Timão\"?", "Corinthians", ["Palmeiras", "Flamengo", "Santos"]],
  [1, "Em qual esporte é disputada a Volta da França (Tour de France)?", "Ciclismo", ["Automobilismo", "Maratona", "Motociclismo"]],
  [1, "No xadrez, qual peça se move em forma de \"L\"?", "Cavalo", ["Bispo", "Torre", "Rainha"]],
  [1, "Em qual país surgiu o futebol moderno?", "Inglaterra", ["Brasil", "Itália", "França"]],
  [2, "Em que ano o Brasil sediou sua primeira Copa do Mundo?", "1950", ["1958", "1970", "2014"]],
  [2, "Qual seleção venceu a primeira Copa do Mundo, em 1930?", "Uruguai", ["Brasil", "Argentina", "Itália"]],
  [2, "Quantos sets um time precisa vencer para ganhar uma partida oficial de vôlei?", "3", ["2", "4", "5"]],
  [2, "Qual tenista brasileiro foi número 1 do mundo e tricampeão de Roland Garros?", "Gustavo Kuerten", ["Fernando Meligeni", "Thomaz Bellucci", "João Fonseca"]],
  [2, "Qual ginasta brasileira ganhou o ouro no salto nos Jogos de Tóquio 2020?", "Rebeca Andrade", ["Daiane dos Santos", "Flávia Saraiva", "Jade Barbosa"]],
  [2, "Qual skatista brasileira ganhou a prata em Tóquio 2020 com apenas 13 anos?", "Rayssa Leal", ["Pâmela Rosa", "Letícia Bufoni", "Karen Jonz"]],
  [2, "No judô, qual pontuação encerra a luta imediatamente?", "Ippon", ["Waza-ari", "Yuko", "Shido"]],
  [2, "Qual piloto foi o primeiro brasileiro campeão mundial de Fórmula 1, em 1972?", "Emerson Fittipaldi", ["Nelson Piquet", "Ayrton Senna", "Rubens Barrichello"]],
  [2, "Qual brasileiro foi eleito melhor jogador do mundo pela FIFA em 2007?", "Kaká", ["Ronaldinho", "Ronaldo", "Rivaldo"]],
  [2, "Qual jogadora brasileira foi eleita seis vezes a melhor do mundo pela FIFA?", "Marta", ["Formiga", "Cristiane", "Sissi"]],
  [2, "Em qual estádio foi disputado o jogo decisivo da Copa de 1950?", "Maracanã", ["Pacaembu", "Morumbi", "Mineirão"]],
  [2, "Como ficou conhecida a derrota do Brasil para o Uruguai na Copa de 1950?", "Maracanazo", ["Mineiraço", "Batalha de Berna", "Tragédia do Sarriá"]],
  [2, "Quantos buracos tem um campo de golfe padrão?", "18", ["9", "12", "21"]],
  [2, "Qual era o esporte de Oscar Schmidt, o \"Mão Santa\"?", "Basquete", ["Vôlei", "Handebol", "Tênis"]],
  [2, "Quantas peças cada jogador tem no início de uma partida de xadrez?", "16", ["12", "18", "20"]],
  [2, "Qual é o comprimento de uma piscina olímpica?", "50 metros", ["25 metros", "100 metros", "75 metros"]],
  [2, "Quantos jogadores de cada time ficam em quadra no futsal?", "5", ["6", "7", "4"]],
  [3, "Quantos pontos vale um touchdown no futebol americano?", "6", ["3", "7", "2"]],
  [3, "Quantos títulos mundiais de Fórmula 1 Nelson Piquet conquistou?", "3", ["2", "1", "4"]],
  [3, "Quem é considerado o responsável por trazer o futebol ao Brasil, em 1894?", "Charles Miller", ["Oscar Cox", "Arthur Friedenreich", "Pelé"]],
  [3, "Quantos jogadores de cada time ficam em quadra no handebol?", "7", ["6", "5", "11"]],
  [3, "Qual lutador brasileiro, apelidado de \"Spider\", dominou o cinturão peso-médio do UFC?", "Anderson Silva", ["Vitor Belfort", "José Aldo", "Junior Cigano"]],
  [3, "Em que ano Ayrton Senna conquistou seu primeiro título mundial de Fórmula 1?", "1988", ["1985", "1990", "1991"]],
  [3, "Qual país venceu a primeira Copa do Mundo de futebol feminino, em 1991?", "Estados Unidos", ["Noruega", "Alemanha", "China"]],
]);

const linguaPortuguesa = bank("lingua-portuguesa", "lin", [
  [1, "Qual é o plural de \"pão\"?", "Pães", ["Pãos", "Pões", "Pãoes"]],
  [1, "Qual é o plural de \"mão\"?", "Mãos", ["Mães", "Mões", "Mãoes"]],
  [1, "Qual é o feminino de \"ator\"?", "Atriz", ["Atora", "Atressa", "Atriza"]],
  [1, "Qual é o coletivo de lobos?", "Alcateia", ["Cardume", "Enxame", "Manada"]],
  [1, "Qual é o coletivo de peixes?", "Cardume", ["Alcateia", "Rebanho", "Bando"]],
  [1, "Qual destas palavras é oxítona (sílaba tônica na última)?", "Café", ["Mesa", "Lâmpada", "Árvore"]],
  [1, "Qual é a grafia correta do verbo que significa \"ver\"?", "Enxergar", ["Enchergar", "Inxergar", "Enxerjar"]],
  [1, "Qual é o aumentativo de \"casa\"?", "Casarão", ["Casinha", "Casebre", "Casario"]],
  [1, "Qual é o diminutivo de \"pé\"?", "Pezinho", ["Pézinho", "Pezão", "Pequeninho"]],
  [1, "Qual destas palavras é um palíndromo (lê-se igual de trás para frente)?", "Arara", ["Casa", "Ovelha", "Mesa"]],
  [2, "Qual é o plural de \"alemão\"?", "Alemães", ["Alemãos", "Alemões", "Alemãns"]],
  [2, "Qual é o plural de \"capitão\"?", "Capitães", ["Capitãos", "Capitões", "Capitãns"]],
  [2, "Qual é o feminino de \"cavalheiro\"?", "Dama", ["Cavalheira", "Amazona", "Senhorita"]],
  [2, "Qual é o coletivo de estrelas?", "Constelação", ["Galáxia", "Arquipélago", "Enxame"]],
  [2, "Qual é o coletivo de ilhas?", "Arquipélago", ["Constelação", "Península", "Continente"]],
  [2, "Qual é o coletivo de cães?", "Matilha", ["Alcateia", "Cáfila", "Vara"]],
  [2, "Qual é o antônimo de \"generoso\"?", "Avarento", ["Bondoso", "Caridoso", "Gentil"]],
  [2, "Qual destas palavras é proparoxítona?", "Lâmpada", ["Cadeira", "Sofá", "Caneta"]],
  [2, "Qual é a grafia correta da palavra que descreve um evento feito para caridade?", "Beneficente", ["Beneficiente", "Benificente", "Beneficênte"]],
  [2, "Qual é a grafia correta da palavra que significa \"vantagem especial\"?", "Privilégio", ["Previlégio", "Privilêgio", "Prevelégio"]],
  [2, "Qual é a grafia correta do verbo que significa \"deixar parado\"?", "Paralisar", ["Paralizar", "Paraliçar", "Parallisar"]],
  [2, "Qual é a grafia correta do legume verde muito usado em sopas e refogados?", "Chuchu", ["Xuxu", "Chuxu", "Xuchu"]],
  [2, "Qual é a classe gramatical de \"rapidamente\"?", "Advérbio", ["Adjetivo", "Verbo", "Substantivo"]],
  [2, "Qual destas palavras é um substantivo?", "Felicidade", ["Feliz", "Felizmente", "Felicitar"]],
  [2, "Qual forma completa a frase: \"Moro aqui ___ dez anos.\"", "há", ["a", "à", "á"]],
  [2, "Qual forma completa a frase: \"Amanhã vou ___ praia.\"", "à", ["a", "há", "á"]],
  [2, "Qual forma completa a frase: \"Ele não é um homem ___.\"", "mau", ["mal", "mais", "mas"]],
  [2, "Quantas letras tem o alfabeto da língua portuguesa hoje?", "26", ["23", "24", "27"]],
  [2, "Qual sinal gráfico o Novo Acordo Ortográfico eliminou de palavras como \"linguiça\" e \"frequente\"?", "Trema", ["Til", "Cedilha", "Acento grave"]],
  [2, "Na frase \"O menino chutou a bola\", qual é o objeto direto?", "a bola", ["o menino", "chutou", "menino"]],
  [3, "Qual é o feminino de \"zangão\"?", "Abelha", ["Zangoa", "Zangona", "Vespa"]],
  [3, "Qual é o sinônimo de \"célere\"?", "Rápido", ["Lento", "Calmo", "Pesado"]],
  [3, "Qual é o sinônimo de \"ímpeto\"?", "Impulso", ["Calma", "Tédio", "Dúvida"]],
  [3, "Qual é o sinônimo de \"idôneo\"?", "Honesto", ["Idoso", "Ingênuo", "Ágil"]],
  [3, "Qual é a grafia correta da palavra que significa \"ideia fixa\"?", "Obsessão", ["Obcessão", "Obseção", "Obsesão"]],
  [3, "Qual é a grafia correta da palavra que significa \"subida\"?", "Ascensão", ["Ascenção", "Acensão", "Assensão"]],
  [3, "Qual é o sujeito da frase \"Choveu muito ontem\"?", "Não há sujeito", ["Muito", "Ontem", "Sujeito oculto: ele"]],
  [3, "Qual forma completa a frase: \"Não sei ___ ele foi embora.\"", "por que", ["porque", "porquê", "por quê"]],
  [3, "Qual figura de linguagem aparece em \"Aquele jogador é um leão\"?", "Metáfora", ["Comparação", "Hipérbole", "Ironia"]],
  [3, "Qual figura de linguagem aparece em \"Chorei rios de lágrimas\"?", "Hipérbole", ["Metonímia", "Eufemismo", "Antítese"]],
  [3, "Qual destas palavras tem um dígrafo?", "Chuva", ["Blusa", "Prato", "Flor"]],
  [3, "Qual é o antônimo de \"ascender\"?", "Descer", ["Subir", "Acender", "Elevar"]],
  [3, "Qual destas palavras é do gênero masculino na norma-padrão?", "Champanhe", ["Alface", "Omoplata", "Cal"]],
]);

const curiosidades = bank("curiosidades", "cur", [
  [1, "Quantos dias tem um ano bissexto?", "366", ["365", "364", "360"]],
  [1, "Qual animal é conhecido como \"rei da selva\"?", "Leão", ["Tigre", "Elefante", "Gorila"]],
  [1, "Qual ave não voa e vive na Antártida?", "Pinguim", ["Avestruz", "Albatroz", "Gaivota"]],
  [1, "Qual é a maior ave do mundo?", "Avestruz", ["Ema", "Condor", "Albatroz"]],
  [1, "Qual réptil é famoso por mudar de cor?", "Camaleão", ["Iguana", "Lagartixa", "Jabuti"]],
  [1, "Quantas patas tem um inseto?", "6", ["4", "8", "10"]],
  [1, "Qual é o maior animal terrestre?", "Elefante-africano", ["Rinoceronte", "Hipopótamo", "Girafa"]],
  [1, "Qual mamífero vive pendurado em árvores e é famoso por se mover muito devagar?", "Bicho-preguiça", ["Tamanduá", "Tatu", "Quati"]],
  [1, "Qual é o maior roedor do mundo?", "Capivara", ["Castor", "Paca", "Porco-espinho"]],
  [1, "Qual é o material natural mais duro?", "Diamante", ["Rubi", "Quartzo", "Granito"]],
  [1, "Qual é a língua oficial de Angola?", "Português", ["Francês", "Inglês", "Suaíli"]],
  [1, "Qual é o ingrediente principal do brigadeiro, além do chocolate?", "Leite condensado", ["Creme de leite", "Doce de leite", "Leite em pó"]],
  [1, "Qual erva é usada para preparar o chimarrão?", "Erva-mate", ["Erva-doce", "Hortelã", "Camomila"]],
  [1, "Qual é o sistema de escrita tátil usado por pessoas cegas?", "Braille", ["Libras", "Morse", "Estenografia"]],
  [1, "Como se chama a língua de sinais oficial do Brasil?", "Libras", ["Braille", "ASL", "Sinalês"]],
  [1, "Como se chama o filhote do cavalo?", "Potro", ["Bezerro", "Cabrito", "Leitão"]],
  [1, "Qual boneco de madeira tem o nariz que cresce quando mente?", "Pinóquio", ["Peter Pan", "Gepeto", "Emília"]],
  [1, "Qual é a identidade secreta do Homem-Aranha?", "Peter Parker", ["Bruce Wayne", "Clark Kent", "Tony Stark"]],
  [1, "Que cor resulta da mistura de azul com amarelo?", "Verde", ["Roxo", "Laranja", "Marrom"]],
  [1, "Qual cidade é conhecida como \"Cidade Maravilhosa\"?", "Rio de Janeiro", ["Salvador", "Florianópolis", "Recife"]],
  [1, "Qual monumento brasileiro foi eleito uma das Sete Maravilhas do Mundo Moderno, em 2007?", "Cristo Redentor", ["Pão de Açúcar", "Congresso Nacional", "Elevador Lacerda"]],
  [1, "Em qual cidade fica a Estátua da Liberdade?", "Nova York", ["Washington", "Paris", "Chicago"]],
  [1, "Em qual cidade italiana fica a famosa torre inclinada?", "Pisa", ["Roma", "Veneza", "Florença"]],
  [1, "Quantos anos dura o mandato de um presidente no Brasil?", "4", ["5", "6", "8"]],
  [2, "Qual é o maior felino das Américas?", "Onça-pintada", ["Puma", "Jaguatirica", "Lince"]],
  [2, "Quantos anos de casamento se comemoram nas bodas de ouro?", "50", ["25", "40", "60"]],
  [2, "Qual é a moeda oficial do Reino Unido?", "Libra esterlina", ["Euro", "Dólar", "Franco"]],
  [2, "Qual idioma tem mais falantes nativos no mundo?", "Mandarim", ["Inglês", "Espanhol", "Hindi"]],
  [2, "Qual cidade italiana é considerada o berço da pizza?", "Nápoles", ["Roma", "Milão", "Veneza"]],
  [2, "Além do queijo, qual é o ingrediente principal do pão de queijo?", "Polvilho", ["Farinha de trigo", "Fubá", "Aveia"]],
  [2, "Em que dia é comemorado o feriado de Tiradentes?", "21 de abril", ["15 de novembro", "12 de outubro", "7 de setembro"]],
  [2, "Como se chama o medo de lugares fechados?", "Claustrofobia", ["Acrofobia", "Agorafobia", "Aracnofobia"]],
  [2, "Quantos lados tem a placa de trânsito \"PARE\"?", "8", ["6", "5", "4"]],
  [2, "Qual é o telefone de emergência do Corpo de Bombeiros no Brasil?", "193", ["190", "192", "199"]],
  [2, "Qual cidade é chamada de \"Terra da Garoa\"?", "São Paulo", ["Curitiba", "Porto Alegre", "Belo Horizonte"]],
  [2, "Qual destes animais costuma dormir em pé?", "Cavalo", ["Cachorro", "Gato", "Coelho"]],
  [2, "Quais são as três cores primárias tradicionais na pintura?", "Vermelho, amarelo e azul", ["Vermelho, verde e azul", "Preto, branco e cinza", "Laranja, verde e roxo"]],
  [3, "Quantos quilates tem o ouro puro?", "24", ["18", "22", "12"]],
  [3, "Qual é a moeda oficial da Índia?", "Rupia", ["Baht", "Dinar", "Rial"]],
  [3, "Em quantos países o português é língua oficial?", "9", ["5", "7", "12"]],
  [3, "O tacacá é um prato típico de qual estado?", "Pará", ["Bahia", "Goiás", "Paraná"]],
  [3, "Quantos fusos horários tem o território brasileiro?", "4", ["3", "2", "5"]],
  [3, "O que mede o barômetro?", "Pressão atmosférica", ["Umidade do ar", "Velocidade do vento", "Temperatura"]],
  [3, "Como se chama o medo de altura?", "Acrofobia", ["Claustrofobia", "Agorafobia", "Aracnofobia"]],
  [3, "De que cor é a \"caixa-preta\" dos aviões?", "Laranja", ["Preta", "Vermelha", "Amarela"]],
  [3, "Em qual planeta um dia dura mais que um ano?", "Vênus", ["Mercúrio", "Marte", "Netuno"]],
  [3, "Quanto tempo, aproximadamente, a luz do Sol leva para chegar à Terra?", "8 minutos", ["8 segundos", "1 hora", "1 dia"]],
  [3, "Qual é a capital mais alta do mundo, a cerca de 3.600 metros de altitude, sede do governo da Bolívia?", "La Paz", ["Quito", "Bogotá", "Sucre"]],
]);

export const QUESTION_BANK: RaceQuestion[] = [
  ...historia,
  ...geografia,
  ...ciencias,
  ...matematica,
  ...tecnologia,
  ...arteCultura,
  ...esportes,
  ...linguaPortuguesa,
  ...curiosidades,
];
